services:
  api-tests:
    build: .
    environment:
      BASE_URL: https://sauce-demo.myshopify.com/
    command: npx playwright test tests/api
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report